name: Python application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 12 * * *" # 每天中午 12 点执行

permissions:
  contents: write # 需要写入 release 目录和创建 releases
  id-token: write # 需要发布 Releases
  actions: write # 需要上传文件到 Releases

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest httpx

      - name: Run Python script
        run: |
          mkdir -p release  # 确保 release 目录存在
          python3 main.py    # 执行 Python 脚本生成 cnip.rsc

      - name: Create GitHub Release
        id: create_release
        run: |
          # 获取当前日期作为版本号
          VERSION=$(date +'%Y-%m-%d-%H-%M-%S')
          echo "Creating release with version: $VERSION"

          # 使用 GitHub CLI 创建 Release
          gh release create $VERSION release/cnip.rsc --title "Release $VERSION" --notes "Automated release for $VERSION"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
